### ISSUE TITLE
建議：加上關閉鈕，使 "自選音效" 選單在行動裝置上更易於關閉

### ISSUE THREAD

**Issue by hit1205** [Rag1995/pop-kemon-vtuber-vite#1]
目前 "自選音效" 選單的關閉方式是：點擊選單以外的空白區域。但在行動裝置（如手機）下，此區域可能會小到很難點擊，想提個建議是：是否可以像主選單一樣，多加一個關閉用的鈕，使其更易於關閉？

**Comment by Rag1995** [comment]
感謝幫忙回報 Bug！
自選音效選單已經增加關閉按鈕囉！感謝！

現在才發現關閉按鈕的 `class name` 只有 `btn-close-white`
沒有加入 light mode 的判斷，導致按鈕永遠是白色的

真沒想到會有人來發 issue 嚇死我了 ((ﾟДﾟ))
